---
- name: "Playbook to deprovision Thoth Core"
  tags:
    - openshift
    - thoth

  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - fail: msg="Bailing out. this play requires 'THOTH_NAMESPACE'"
    when: THOTH_NAMESPACE is not defined

  - name: "Deprovision Thoth components"
    command: "oc delete bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,template,clusterrole --selector 'app=thoth'"

  - name: "Deprovision Thoth ServiceAccounts"
    command: "oc delete sa --selector 'app=thoth'"
