---
- name: Playbook to provision Thoth Core
    - openshift
    - thoth

  hosts: localhost
  vars:
    openshift_master_url: "{{ lookup('env','OCP_URL') }}"
    token: "{{ lookup('env','OCP_TOKEN') }}"
    THOTH_BACKEND_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_MIDDLEEND_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_MIDDLETIER_NAMESPACE: "{{ THOTH_MIDDLEEND_NAMESPACE }}"
    THOTH_FRONTEND_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_INFRA_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_DEPLOYMENT_NAME: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_CEPH_SECRET_KEY: "{{ lookup('env','THOTH_CEPH_SECRET_KEY') }}"
    THOTH_CEPH_KEY_ID: "{{ lookup('env','THOTH_CEPH_KEY_ID') }}"
    THOTH_CEPH_HOST: "{{ lookup('env','THOTH_CEPH_HOST') }}"
    THOTH_CEPH_BUCKET: "DH-DEV-DATA"
    THOTH_SECRET: "{{ lookup('env','THOTH_SECRET') }}"
    
  gather_facts: false
  connection: local
  roles:
  - role: thoth-core
  - role: thoth-station.thoth-core-imagestreams
  - role: thoth-frontend
  - role: thoth-middletier
  - role: thoth-backend
  - role: thoth-infra-buildconfigs
  - role: thoth-jenkins
